### ISSUE TITLE
Number appears below icon

### ISSUE THREAD

**Issue by SuperDisk** [BlackYoup/outlook-notifier#16]
![screen shot 2015-04-18 at 11 32 43 pm](https://cloud.githubusercontent.com/assets/1688837/7218036/3b0bc982-e623-11e4-8654-ae751a00e253.png)

I'm not sure if this is some sort of bug or if it's able to be remedied, but on Macintosh OS X Yosemite, Firefox, 37.0.1 it looks like this. When there's no emails, the number goes away and the menubar shrinks again to its normal size.

**Comment by BlackYoup** [comment]
Yeah, someone already reported this bug and I tried to fix but no luck so far. I don't know why but Firefox act differently on Mac OS X compared to Linux or Windows. I have only one idea of how to fix this, I'll have to look into it

**Comment by BlackYoup** [comment]
I've made an update request to Mozilla, so expect the addon to be updated soon. It should fix this bug, will wait to hear from you @SuperDisk !

**Comment by SuperDisk** [comment]
I'll keep you posted! Thanks for the handy extension.

**Comment by BlackYoup** [comment]
@SuperDisk are we good here ?

**Comment by SuperDisk** [comment]
Yup, I believe you fixed it an update ago. I'm sorry, I thought I posted! Thanks.

**Comment by BlackYoup** [comment]
Yep, no problem :)
